// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/weather.proto

package weather

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coord struct {
	Lon                  float64  `protobuf:"fixed64,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{0}
}

func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Coord) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Weather struct {
	Id                   float64  `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Main                 string   `protobuf:"bytes,2,opt,name=main,proto3" json:"main,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weather) Reset()         { *m = Weather{} }
func (m *Weather) String() string { return proto.CompactTextString(m) }
func (*Weather) ProtoMessage()    {}
func (*Weather) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{1}
}

func (m *Weather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weather.Unmarshal(m, b)
}
func (m *Weather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weather.Marshal(b, m, deterministic)
}
func (m *Weather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weather.Merge(m, src)
}
func (m *Weather) XXX_Size() int {
	return xxx_messageInfo_Weather.Size(m)
}
func (m *Weather) XXX_DiscardUnknown() {
	xxx_messageInfo_Weather.DiscardUnknown(m)
}

var xxx_messageInfo_Weather proto.InternalMessageInfo

func (m *Weather) GetId() float64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Weather) GetMain() string {
	if m != nil {
		return m.Main
	}
	return ""
}

func (m *Weather) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Weather) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type Main struct {
	Temp                 float64  `protobuf:"fixed64,1,opt,name=temp,proto3" json:"temp,omitempty"`
	FeelsLike            float64  `protobuf:"fixed64,3,opt,name=feels_like,json=feelsLike,proto3" json:"feels_like,omitempty"`
	TempMin              float64  `protobuf:"fixed64,4,opt,name=temp_min,json=tempMin,proto3" json:"temp_min,omitempty"`
	TempMax              float64  `protobuf:"fixed64,5,opt,name=temp_max,json=tempMax,proto3" json:"temp_max,omitempty"`
	Pressure             float64  `protobuf:"fixed64,6,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Humidity             float64  `protobuf:"fixed64,7,opt,name=humidity,proto3" json:"humidity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Main) Reset()         { *m = Main{} }
func (m *Main) String() string { return proto.CompactTextString(m) }
func (*Main) ProtoMessage()    {}
func (*Main) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{2}
}

func (m *Main) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Main.Unmarshal(m, b)
}
func (m *Main) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Main.Marshal(b, m, deterministic)
}
func (m *Main) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Main.Merge(m, src)
}
func (m *Main) XXX_Size() int {
	return xxx_messageInfo_Main.Size(m)
}
func (m *Main) XXX_DiscardUnknown() {
	xxx_messageInfo_Main.DiscardUnknown(m)
}

var xxx_messageInfo_Main proto.InternalMessageInfo

func (m *Main) GetTemp() float64 {
	if m != nil {
		return m.Temp
	}
	return 0
}

func (m *Main) GetFeelsLike() float64 {
	if m != nil {
		return m.FeelsLike
	}
	return 0
}

func (m *Main) GetTempMin() float64 {
	if m != nil {
		return m.TempMin
	}
	return 0
}

func (m *Main) GetTempMax() float64 {
	if m != nil {
		return m.TempMax
	}
	return 0
}

func (m *Main) GetPressure() float64 {
	if m != nil {
		return m.Pressure
	}
	return 0
}

func (m *Main) GetHumidity() float64 {
	if m != nil {
		return m.Humidity
	}
	return 0
}

type Wind struct {
	Speed                float64  `protobuf:"fixed64,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Deg                  float64  `protobuf:"fixed64,2,opt,name=deg,proto3" json:"deg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wind) Reset()         { *m = Wind{} }
func (m *Wind) String() string { return proto.CompactTextString(m) }
func (*Wind) ProtoMessage()    {}
func (*Wind) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{3}
}

func (m *Wind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wind.Unmarshal(m, b)
}
func (m *Wind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wind.Marshal(b, m, deterministic)
}
func (m *Wind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wind.Merge(m, src)
}
func (m *Wind) XXX_Size() int {
	return xxx_messageInfo_Wind.Size(m)
}
func (m *Wind) XXX_DiscardUnknown() {
	xxx_messageInfo_Wind.DiscardUnknown(m)
}

var xxx_messageInfo_Wind proto.InternalMessageInfo

func (m *Wind) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Wind) GetDeg() float64 {
	if m != nil {
		return m.Deg
	}
	return 0
}

type Clouds struct {
	All                  float64  `protobuf:"fixed64,1,opt,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clouds) Reset()         { *m = Clouds{} }
func (m *Clouds) String() string { return proto.CompactTextString(m) }
func (*Clouds) ProtoMessage()    {}
func (*Clouds) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{4}
}

func (m *Clouds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clouds.Unmarshal(m, b)
}
func (m *Clouds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clouds.Marshal(b, m, deterministic)
}
func (m *Clouds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clouds.Merge(m, src)
}
func (m *Clouds) XXX_Size() int {
	return xxx_messageInfo_Clouds.Size(m)
}
func (m *Clouds) XXX_DiscardUnknown() {
	xxx_messageInfo_Clouds.DiscardUnknown(m)
}

var xxx_messageInfo_Clouds proto.InternalMessageInfo

func (m *Clouds) GetAll() float64 {
	if m != nil {
		return m.All
	}
	return 0
}

type Sys struct {
	Type                 float64  `protobuf:"fixed64,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   float64  `protobuf:"fixed64,2,opt,name=id,proto3" json:"id,omitempty"`
	Message              float64  `protobuf:"fixed64,3,opt,name=message,proto3" json:"message,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Sunrise              float64  `protobuf:"fixed64,5,opt,name=sunrise,proto3" json:"sunrise,omitempty"`
	Sunset               float64  `protobuf:"fixed64,6,opt,name=sunset,proto3" json:"sunset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sys) Reset()         { *m = Sys{} }
func (m *Sys) String() string { return proto.CompactTextString(m) }
func (*Sys) ProtoMessage()    {}
func (*Sys) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{5}
}

func (m *Sys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sys.Unmarshal(m, b)
}
func (m *Sys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sys.Marshal(b, m, deterministic)
}
func (m *Sys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sys.Merge(m, src)
}
func (m *Sys) XXX_Size() int {
	return xxx_messageInfo_Sys.Size(m)
}
func (m *Sys) XXX_DiscardUnknown() {
	xxx_messageInfo_Sys.DiscardUnknown(m)
}

var xxx_messageInfo_Sys proto.InternalMessageInfo

func (m *Sys) GetType() float64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Sys) GetId() float64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sys) GetMessage() float64 {
	if m != nil {
		return m.Message
	}
	return 0
}

func (m *Sys) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Sys) GetSunrise() float64 {
	if m != nil {
		return m.Sunrise
	}
	return 0
}

func (m *Sys) GetSunset() float64 {
	if m != nil {
		return m.Sunset
	}
	return 0
}

type CurrentWeatherResponse struct {
	Coord                *Coord     `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
	Weather              []*Weather `protobuf:"bytes,2,rep,name=weather,proto3" json:"weather,omitempty"`
	Main                 *Main      `protobuf:"bytes,3,opt,name=main,proto3" json:"main,omitempty"`
	Wind                 *Wind      `protobuf:"bytes,4,opt,name=wind,proto3" json:"wind,omitempty"`
	Sys                  *Sys       `protobuf:"bytes,5,opt,name=sys,proto3" json:"sys,omitempty"`
	Clouds               *Clouds    `protobuf:"bytes,6,opt,name=clouds,proto3" json:"clouds,omitempty"`
	Name                 string     `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CurrentWeatherResponse) Reset()         { *m = CurrentWeatherResponse{} }
func (m *CurrentWeatherResponse) String() string { return proto.CompactTextString(m) }
func (*CurrentWeatherResponse) ProtoMessage()    {}
func (*CurrentWeatherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{6}
}

func (m *CurrentWeatherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentWeatherResponse.Unmarshal(m, b)
}
func (m *CurrentWeatherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentWeatherResponse.Marshal(b, m, deterministic)
}
func (m *CurrentWeatherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentWeatherResponse.Merge(m, src)
}
func (m *CurrentWeatherResponse) XXX_Size() int {
	return xxx_messageInfo_CurrentWeatherResponse.Size(m)
}
func (m *CurrentWeatherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentWeatherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentWeatherResponse proto.InternalMessageInfo

func (m *CurrentWeatherResponse) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *CurrentWeatherResponse) GetWeather() []*Weather {
	if m != nil {
		return m.Weather
	}
	return nil
}

func (m *CurrentWeatherResponse) GetMain() *Main {
	if m != nil {
		return m.Main
	}
	return nil
}

func (m *CurrentWeatherResponse) GetWind() *Wind {
	if m != nil {
		return m.Wind
	}
	return nil
}

func (m *CurrentWeatherResponse) GetSys() *Sys {
	if m != nil {
		return m.Sys
	}
	return nil
}

func (m *CurrentWeatherResponse) GetClouds() *Clouds {
	if m != nil {
		return m.Clouds
	}
	return nil
}

func (m *CurrentWeatherResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	Cities               []string `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{7}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCities() []string {
	if m != nil {
		return m.Cities
	}
	return nil
}

type Response struct {
	Response             []*CurrentWeatherResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{8}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse() []*CurrentWeatherResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Coord)(nil), "Coord")
	proto.RegisterType((*Weather)(nil), "Weather")
	proto.RegisterType((*Main)(nil), "Main")
	proto.RegisterType((*Wind)(nil), "Wind")
	proto.RegisterType((*Clouds)(nil), "Clouds")
	proto.RegisterType((*Sys)(nil), "Sys")
	proto.RegisterType((*CurrentWeatherResponse)(nil), "CurrentWeatherResponse")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() {
	proto.RegisterFile("proto/weather.proto", fileDescriptor_ecdc6c2fb8d35c9c)
}

var fileDescriptor_ecdc6c2fb8d35c9c = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0xb1, 0x63, 0x3b, 0x63, 0xa9, 0x42, 0x0b, 0x2a, 0x6e, 0x04, 0x22, 0xf8, 0x14, 0x09,
	0xc9, 0x48, 0xee, 0x07, 0x70, 0xc8, 0x81, 0x0b, 0xbd, 0x6c, 0x0e, 0x3d, 0x56, 0xc6, 0x1e, 0xd2,
	0x55, 0xed, 0xb5, 0xd9, 0x5d, 0xd3, 0xfa, 0x2b, 0xf8, 0x0c, 0xbe, 0x8a, 0x7f, 0x41, 0x3b, 0xde,
	0x0d, 0x3d, 0x70, 0x9b, 0xf7, 0xde, 0xcc, 0x38, 0xef, 0xed, 0x04, 0x5e, 0x8d, 0x6a, 0x30, 0xc3,
	0xa7, 0x47, 0xac, 0xcd, 0x3d, 0xaa, 0x92, 0x50, 0xf1, 0x11, 0xd6, 0x87, 0x61, 0x50, 0x2d, 0x7b,
	0x09, 0x61, 0x37, 0xc8, 0x3c, 0xd8, 0x05, 0xfb, 0x80, 0xdb, 0x92, 0x98, 0xda, 0xe4, 0x2b, 0xc7,
	0xd4, 0xa6, 0x68, 0x20, 0xb9, 0x5d, 0xa6, 0xd9, 0x05, 0xac, 0x44, 0xeb, 0xba, 0x57, 0xa2, 0x65,
	0x0c, 0xa2, 0xbe, 0x16, 0x92, 0xba, 0x37, 0x9c, 0x6a, 0xb6, 0x83, 0xac, 0x45, 0xdd, 0x28, 0x31,
	0x1a, 0x31, 0xc8, 0x3c, 0x24, 0xe9, 0x39, 0x65, 0xa7, 0x44, 0x33, 0xc8, 0x3c, 0x5a, 0xa6, 0x6c,
	0x5d, 0xfc, 0x0e, 0x20, 0xba, 0xb1, 0xe3, 0x0c, 0x22, 0x83, 0xfd, 0xe8, 0x3e, 0x42, 0x35, 0x7b,
	0x07, 0xf0, 0x1d, 0xb1, 0xd3, 0x77, 0x9d, 0x78, 0x40, 0xda, 0x18, 0xf0, 0x0d, 0x31, 0x5f, 0xc5,
	0x03, 0xb2, 0x2b, 0x48, 0x6d, 0xdb, 0x5d, 0x2f, 0x96, 0x9d, 0x01, 0x4f, 0x2c, 0xbe, 0x11, 0xf2,
	0x9f, 0x54, 0x3f, 0xe5, 0xeb, 0x67, 0x52, 0xfd, 0xc4, 0xb6, 0x90, 0x8e, 0x0a, 0xb5, 0x9e, 0x14,
	0xe6, 0x31, 0x49, 0x67, 0x6c, 0xb5, 0xfb, 0xa9, 0x17, 0xad, 0x30, 0x73, 0x9e, 0x2c, 0x9a, 0xc7,
	0x45, 0x09, 0xd1, 0xad, 0x90, 0x2d, 0x7b, 0x0d, 0x6b, 0x3d, 0x22, 0xfa, 0x38, 0x16, 0x60, 0xe3,
	0x6b, 0xf1, 0xe4, 0xe3, 0x6b, 0xf1, 0x54, 0x6c, 0x21, 0x3e, 0x74, 0xc3, 0xd4, 0x6a, 0xab, 0xd5,
	0x5d, 0xe7, 0xc3, 0xae, 0xbb, 0xae, 0xf8, 0x15, 0x40, 0x78, 0x9c, 0x35, 0x99, 0x9e, 0x47, 0x3c,
	0x9b, 0x9e, 0x47, 0x74, 0x59, 0xaf, 0xce, 0x59, 0xe7, 0x90, 0xf4, 0xa8, 0x75, 0x7d, 0xf2, 0x09,
	0x78, 0x68, 0x95, 0x66, 0x98, 0xa4, 0x51, 0xb3, 0x8b, 0xd4, 0x43, 0xab, 0xe8, 0x49, 0x2a, 0xa1,
	0xd1, 0xbb, 0x77, 0x90, 0x5d, 0x42, 0xac, 0x27, 0xa9, 0xd1, 0x38, 0xef, 0x0e, 0x15, 0x7f, 0x02,
	0xb8, 0x3c, 0x4c, 0x4a, 0xa1, 0x34, 0xee, 0xd1, 0x39, 0xea, 0x71, 0x90, 0x1a, 0xd9, 0x5b, 0x58,
	0x37, 0xf6, 0x68, 0xe8, 0x57, 0x66, 0x55, 0x5c, 0xd2, 0x09, 0xf1, 0x85, 0x64, 0x05, 0x24, 0xee,
	0xc6, 0xf2, 0xd5, 0x2e, 0xdc, 0x67, 0x55, 0x5a, 0xfa, 0x05, 0x5e, 0x60, 0x57, 0xee, 0x5c, 0x42,
	0x5a, 0xb0, 0x2e, 0xed, 0x83, 0xbb, 0xab, 0xb9, 0x82, 0xe8, 0x51, 0xc8, 0x96, 0x0c, 0x58, 0xc9,
	0x46, 0xcc, 0x89, 0x62, 0x97, 0x10, 0xea, 0x59, 0x93, 0x81, 0xac, 0x8a, 0xca, 0xe3, 0xac, 0xb9,
	0x25, 0xd8, 0x7b, 0x88, 0x1b, 0x0a, 0x96, 0x2c, 0x64, 0x55, 0x52, 0x2e, 0x39, 0x73, 0x47, 0xdb,
	0x54, 0x65, 0xdd, 0x23, 0xbd, 0xe0, 0x86, 0x53, 0x5d, 0x7c, 0x80, 0x84, 0xe3, 0x8f, 0x09, 0xb5,
	0xb1, 0x11, 0x34, 0xc2, 0x08, 0xd4, 0x79, 0xb0, 0x0b, 0xf7, 0x1b, 0xee, 0x50, 0xf1, 0x19, 0xd2,
	0xb3, 0xe7, 0x6b, 0x48, 0x95, 0xab, 0xa9, 0x2b, 0xab, 0xde, 0x94, 0xff, 0x8f, 0x87, 0x9f, 0x1b,
	0xab, 0x12, 0x2e, 0x9c, 0x78, 0x44, 0xf5, 0x53, 0x34, 0x36, 0xba, 0xf0, 0x0b, 0x1a, 0x96, 0x96,
	0xee, 0xdb, 0xdb, 0x4d, 0xe9, 0xe7, 0x8a, 0x17, 0xdf, 0x62, 0xfa, 0x53, 0x5e, 0xff, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xd5, 0xed, 0x6f, 0x68, 0xab, 0x03, 0x00, 0x00,
}
