// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/weather.proto

package weather

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for WeatherService service

type WeatherService interface {
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type weatherService struct {
	c    client.Client
	name string
}

func NewWeatherService(name string, c client.Client) WeatherService {
	return &weatherService{
		c:    c,
		name: name,
	}
}

func (c *weatherService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WeatherService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WeatherService service

type WeatherServiceHandler interface {
	Get(context.Context, *Request, *Response) error
}

func RegisterWeatherServiceHandler(s server.Server, hdlr WeatherServiceHandler, opts ...server.HandlerOption) error {
	type weatherService interface {
		Get(ctx context.Context, in *Request, out *Response) error
	}
	type WeatherService struct {
		weatherService
	}
	h := &weatherServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&WeatherService{h}, opts...))
}

type weatherServiceHandler struct {
	WeatherServiceHandler
}

func (h *weatherServiceHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.WeatherServiceHandler.Get(ctx, in, out)
}
